---
- name: create webhook namespace
  k8s:
    state: present
    definition: "{{ lookup('template', 'namespace.yml.j2') }}"

- name: Install webhook helm chart
  helm:
    host: "{{ l_helm_host }}"
    port: "{{ l_helm_port }}"
    chart:
      name: vault-secrets-webhook
      version: "{{ vault_webhook_helm_chart_version }}"
      source:
        type: git
        location: https://github.com/banzaicloud/banzai-charts.git
        reference: "vault-secrets-webhook/{{ vault_webhook_helm_chart_version }}"
        path: vault-secrets-webhook
    values: "{{ vault_webhook_helm_values }}"
    state: present
    name: "{{ vault_webhook_helm_release_name }}"
    namespace: "{{ vault_webhook_helm_namespace }}"
