---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: rancher
    box: centos/7
    cpus: 1
    memory: 4096
    interfaces:
      - auto_config: true
        ip: 172.28.128.3
        network_name: private_network
        type: static
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      rancher:
        rancher_rke_install: true
        rancher_helm_chart_install: true
        rancher_letsencrypt_setup: false
        rke_nodes:
          - address: 172.28.128.3
            user: vagrant
            role: [controlplane, etcd, worker]
        vault_crd_helm_values:
          ingress:
            enabled: true
            hosts:
              - vault.172.28.128.3.xip.io
            annotations:
              kubernetes.io/ingress.class: nginx

          persistence:
            ## Enable persistence using Persistent Volume Claims
            ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
            enabled: false

          vault:
            externalConfig:
              # Allows creating policies in Vault which can be used later on in roles
              # for the Kubernetes based authentication.
              # See https://www.vaultproject.io/docs/concepts/policies.html for more information.
              policies:
                - name: allow_secrets
                  rules: path "secret/*" {
                          capabilities = ["create", "read", "update", "delete", "list"]
                        }
              auth:
                - type: kubernetes
                  # Allows creating roles in Vault which can be used later on for the Kubernetes based
                  # authentication.
                  # See https://www.vaultproject.io/docs/auth/kubernetes.html#creating-a-role for
                  # more information.
                  roles:
                    # Allow every pod in the default namespace to use the secret kv store
                    - name: jenkins
                      bound_service_account_names: default
                      bound_service_account_namespaces: jenkins
                      policies: allow_secrets
                      ttl: 1h
              secrets:
                - path: secret
                  type: kv
                  description: General secrets.
                  options:
                    version: 2
            config:
              # A YAML representation of a final vault config.json file.
              # See https://www.vaultproject.io/docs/configuration/ for more information.
              listener:
                tcp:
                  tls_disable: true

              # See https://www.vaultproject.io/docs/configuration/storage/ for storage backends
              storage:
                file:
                  path: "/vault/file"

            logLevel: debug

  lint:
    name: ansible-lint
    options:
      x: [
        "204"  # Lines should be no longer than 160 chars
      ]
verifier:
  name: testinfra
  lint:
    name: flake8
